### ISSUE TITLE
Dicionario censo 2000 e 2010

### ISSUE THREAD

**Issue by rafapereirabr** [erickrf/dicionariosIBGE#2]
Oi Erick, voce tem planos de atualizar o pacote incluindo os dicionarios do censo demografico 2000 e 2010 ?

**Comment by erickrf** [comment]
Não, eu não trabalho mais com esse tema há bastante tempo. Que eu saiba, quem tem uma versão mais atualizada é o Alexandre Rademaker: https://github.com/arademaker/dicionariosIBGE

**Comment by rafapereirabr** [comment]
Ok. Obrigado
